"""add admin audit logs

Revision ID: d821e9e9fb26
Revises: 530c55c319d2
Create Date: 2026-10-10 14:28:18.847984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd821e9e9fb26'
down_revision: Union[str, Sequence[str], None] = '530c55c319d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_title', sa.String(length=200), nullable=False),
    sa.Column('target_owner_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_admin_audit_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_admin_audit_target_id', ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_audit_target_id')
        batch_op.drop_index('ix_admin_audit_created_at')

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
